### ISSUE TITLE
Allow Using Official Syncthing Binary

### ISSUE THREAD

**Issue by PhasecoreX** [Azure-Agst/decky-syncthing#4]
Hello!

I am using the official Syncthing binary, located at https://syncthing.net/downloads/, the Linux Intel/AMD (64‑bit) variant. I run it with systemd as an enabled user service, everything works nicely.

It's running on port 8384, however for some reason this plugin doesn't want to connect to it. If I select the globe icon in the plugin, it does open the browser to Syncthing, and I can see it working just fine. Curiously, the browser is opened to http://127.0.0.1:58384, not sure where the 5 in the port is coming from or how that's still working... but it does. In desktop mode the 8384 works as expected, I didn't try 58384.

Wasn't sure if there was something I was doing wrong? I'd assume flatpak or not, the port is the same and so it should still work?

Any help would be appreciated!

**Comment by Azure-Agst** [comment]
Globe icon? I think you have the wrong plugin lol. You must be talking about the plugin (of the same name) from the official decky repo.

Try reporting your issue here: https://github.com/theCapypara/steamdeck-decky-syncthing

**Comment by PhasecoreX** [comment]
Oh, I had no idea there were two. Thanks for pointing me in the right direction!

**Comment by Azure-Agst** [comment]
It's totally fine! I realized the creator of the official plugin decided to name his project the exact same as mine, so I've added a disclaimer to the README and also the issue template to hopefully prevent this stuff from happening to other folks.

Have a good one!
