### ISSUE TITLE
TypeError: Failed to fetch/Mismatched ports

### ISSUE THREAD

**Issue by Azure-Agst** [Azure-Agst/decky-syncthing#5]
Converted into a new issue to prevent notifying other users

-----

> Hi! Same issue here. I am running on SteamOS 3.5.19 and Syncthing version 0.9.4.5, configured it to run on boot in desktop and game mode.
The logs are empty, and the only error I see is "State: !!! failed loading: TypeError: Failed to fetch"
> A few interesting things I've noticed though, pressing the web button in the plugin always brings me to 127.0.0.1:58384, even if I set my port to be 8081 (my SyncThing was running on that port and was set as such in the plugin settings). I changed it to 58384, which makes the web button work properly, but the plugin still gives the same error.

_Originally posted by @ThePerfectVale in https://github.com/Azure-Agst/decky-syncthing/issues/3#issuecomment-2227046271_

**Comment by Azure-Agst** [comment]
Hey @ThePerfectVale, I'd be happy to help.

First question: How did you install this plugin? Was it via decky store? If so, you're probably using the plugin from [this repo](https://github.com/theCapypara/steamdeck-decky-syncthing) instead. If you installed using the instructions in this repo's README however, then I'll probably be of more help.

**Comment by ThePerfectVale** [comment]
Hi again! My bad, I was unaware that there were two repo's for this, I installed it from the decky store.
I do want to try out if your version works better. Might be a dumb question, but is it possible to build your version of the plugin on Windows? The "make" command doesn't seem to be available on my system.

**Comment by Azure-Agst** [comment]
I've really gotta get my GitHub notifications working better.

I'm unsure, I've always developed these plugins on Linux via WSL. Installing Ubuntu via WSL then building that way might be an option, but I figure it's more hassle than it's worth.

IIRC if you enable developer mode, there's a way you can install from a zip file. Might be worth looking into. I'll see if I can make a release here after I've updated it.

**Comment by Azure-Agst** [comment]
Here we go. I uploaded an updated zip after messing with the convoluted plugin loader toolchain for like an hour.

https://github.com/Azure-Agst/decky-syncthing/releases/download/v0.1.0a/Azure-Syncthing.zip

You can use that link to install the plugin via the developer menu. It might honestly be easier to download the file in desktop mode, then boot back into gaming mode and install with the "Install from zip" option.

Just make sure you restart your deck after you install, or else I've noticed the plugin gets stuck on a "Loading... (State: -99)" screen.
